### ISSUE TITLE
Matrix Addition

### ISSUE THREAD

**Issue by SoumyadeepMukherjee** [SoumyadeepMukherjee/Matrix_Manipulation#1]
Any types of programming languages are accepted.

**Comment by aniket-24** [comment]
Please assign me this issue under Hacktoberfest!

**Comment by abirbhattacharya82** [comment]
Hello Soumyadeep can you please assign me this issue?

**Comment by Abhicoder03** [comment]
Hey @SoumyadeepMukherjee ..Please assign this to me under hacktoberfest.
